### ISSUE TITLE
Options.ini bug 

### ISSUE THREAD

**Issue by luka-11** [Ravo92/Patch-2.22-Launcher#8]
![launcher](https://user-images.githubusercontent.com/119858510/206937877-c607eb1c-d046-4029-8e79-af8f040c1fc8.jpg)
 error deatils See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not find file 'C:\Users\PC\AppData\Roaming\My Battle for Middle-earth Files\Options.ini'.
File name: 'C:\Users\PC\AppData\Roaming\My Battle for Middle-earth Files\Options.ini'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at Helper.OptionIniParser.ReadKey(String keyName)
   at PatchLauncher.OptionsBFME1..ctor() in C:\GIT\Patch-2.22-Launcher\BFME1\OptionsBFME1.cs:line 209
   at PatchLauncher.BFME1.BtnOptions_Click(Object sender, EventArgs e) in C:\GIT\Patch-2.22-Launcher\BFME1\BFME1.cs:line 286
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Private.CoreLib.dll
----------------------------------------
PatchLauncherBFME1
    Assembly Version: 1.0.1.1
    Win32 Version: 1.0.1.1
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/PatchLauncherBFME1.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Collections.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Drawing.Common.dll
----------------------------------------
Helper
    Assembly Version: 1.0.1.1
    Win32 Version: 1.0.1.1
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/Helper.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/Microsoft.Win32.Registry.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.ObjectModel.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.ComponentModel.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Private.Uri.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Memory.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Linq.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Private.Xml.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Text.RegularExpressions.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Net.WebClient.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Text.Encoding.Extensions.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Threading.Thread.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Xml.XmlSerializer.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Windows.Extensions.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/Microsoft.Win32.Primitives.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/Accessibility.dll
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.1462.37
    Win32 Version: 1.0.1462.37
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/Microsoft.Web.WebView2.WinForms.dll
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.1462.37
    Win32 Version: 1.0.1462.37
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/Microsoft.Web.WebView2.Core.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/mscorlib.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Collections.Concurrent.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Numerics.Vectors.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Drawing.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Threading.Tasks.dll
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Net.NameResolution.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Threading.ThreadPool.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Collections.NonGeneric.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
SharpDX.XAudio2
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/SharpDX.XAudio2.dll
----------------------------------------
SharpDX
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/SharpDX.dll
----------------------------------------
System.Reflection.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Reflection.Extensions.dll
----------------------------------------
System.Reflection
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Reflection.dll
----------------------------------------
System.IO
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.IO.dll
----------------------------------------
System.Globalization
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Globalization.dll
----------------------------------------
Downloader
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1.0
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/Downloader.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Net.ServicePoint
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Net.ServicePoint.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Reflection.Primitives.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Net.Requests.dll
----------------------------------------
System.IO.FileSystem.DriveInfo
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.IO.FileSystem.DriveInfo.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Runtime.Loader.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.Collections.Immutable.dll
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1122.52304
    CodeBase: file:///C:/Users/PC/AppData/Roaming/Patch%202.22%20Launcher/System.IO.MemoryMappedFiles.dll
----------------------------------------

************** JIT Debugging **************

**Comment by luka-11** [comment]
this happens when the launcher is downloading\installing the game and i try to open Options folder

**Comment by luka-11** [comment]
this also happens when i try saving my changes in Options, if i press Yes it doesnt do anything,  No does the thing you want
